name: Build React app and Push to Build Branch 
on:
  push:
    branches:
      [master]
jobs:
  deploy:
    if: ${{ github.event.head_commit.message == 'deploy' }}
    name: Deploy React App
    runs-on: [ubuntu-latest]
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        name: Use Node.js 14
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
        env:
          CI: false

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.github_token }}
          publish_branch: build
          publish_dir: build

  test:
    if: ${{ github.event.head_commit.message == 'test' }}
    name: Test React App
    runs-on: [ubuntu-latest]
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        name: Use Node.js 14
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Test App
        run: npm run test